//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captura.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Captura.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on Top.
        /// </summary>
        public static string AlwaysOnTop {
            get {
                return ResourceManager.GetString("AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captura.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Saved.
        /// </summary>
        public static string AudioSaved {
            get {
                return ResourceManager.GetString("AudioSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Color.
        /// </summary>
        public static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Color.
        /// </summary>
        public static string BorderColor {
            get {
                return ResourceManager.GetString("BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Thickness.
        /// </summary>
        public static string BorderThickness {
            get {
                return ResourceManager.GetString("BorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Duration (in seconds).
        /// </summary>
        public static string CaptureDuration {
            get {
                return ResourceManager.GetString("CaptureDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Recent List.
        /// </summary>
        public static string ClearRecentList {
            get {
                return ResourceManager.GetString("ClearRecentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Output file path to Clipboard.
        /// </summary>
        public static string CopyOutPathClipboard {
            get {
                return ResourceManager.GetString("CopyOutPathClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path.
        /// </summary>
        public static string CopyPath {
            get {
                return ResourceManager.GetString("CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner Radius.
        /// </summary>
        public static string CornerRadius {
            get {
                return ResourceManager.GetString("CornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Click and Keystrokes Overlays.
        /// </summary>
        public static string CustomizeClickAndKeysOverlays {
            get {
                return ResourceManager.GetString("CustomizeClickAndKeysOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay cannot be greater than Duration.
        /// </summary>
        public static string DelayGtDuration {
            get {
                return ResourceManager.GetString("DelayGtDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk.
        /// </summary>
        public static string Disk {
            get {
                return ResourceManager.GetString("Disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFMpeg Folder.
        /// </summary>
        public static string FFMpegFolder {
            get {
                return ResourceManager.GetString("FFMpegFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFMpeg Log.
        /// </summary>
        public static string FFMpegLog {
            get {
                return ResourceManager.GetString("FFMpegLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        public static string Flip {
            get {
                return ResourceManager.GetString("Flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Rate.
        /// </summary>
        public static string FrameRate {
            get {
                return ResourceManager.GetString("FrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gif.
        /// </summary>
        public static string Gif {
            get {
                return ResourceManager.GetString("Gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide on Full Screen ScreenShot.
        /// </summary>
        public static string HideOnFullScreenShot {
            get {
                return ResourceManager.GetString("HideOnFullScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Saved. Image taken was Empty.
        /// </summary>
        public static string ImgEmpty {
            get {
                return ResourceManager.GetString("ImgEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Format.
        /// </summary>
        public static string ImgFormat {
            get {
                return ResourceManager.GetString("ImgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Saved to Clipboard.
        /// </summary>
        public static string ImgSavedClipboard {
            get {
                return ResourceManager.GetString("ImgSavedClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Saved to Disk.
        /// </summary>
        public static string ImgSavedDisk {
            get {
                return ResourceManager.GetString("ImgSavedDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imgur.
        /// </summary>
        public static string Imgur {
            get {
                return ResourceManager.GetString("Imgur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imgur Upload Failed.
        /// </summary>
        public static string ImgurFailed {
            get {
                return ResourceManager.GetString("ImgurFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imgur Upload Successful.
        /// </summary>
        public static string ImgurSuccess {
            get {
                return ResourceManager.GetString("ImgurSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading to Imgur.
        /// </summary>
        public static string ImgurUploading {
            get {
                return ResourceManager.GetString("ImgurUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Mouse Clicks.
        /// </summary>
        public static string IncludeClicks {
            get {
                return ResourceManager.GetString("IncludeClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Cursor.
        /// </summary>
        public static string IncludeCursor {
            get {
                return ResourceManager.GetString("IncludeCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include KeyStrokes.
        /// </summary>
        public static string IncludeKeys {
            get {
                return ResourceManager.GetString("IncludeKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keystrokes.
        /// </summary>
        public static string Keystrokes {
            get {
                return ResourceManager.GetString("Keystrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker Output Source.
        /// </summary>
        public static string LoopbackSource {
            get {
                return ResourceManager.GetString("LoopbackSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max items to persist.
        /// </summary>
        public static string MaxRecent {
            get {
                return ResourceManager.GetString("MaxRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Text Length.
        /// </summary>
        public static string MaxTextLength {
            get {
                return ResourceManager.GetString("MaxTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Source.
        /// </summary>
        public static string MicSource {
            get {
                return ResourceManager.GetString("MicSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize on Capture Start.
        /// </summary>
        public static string MinCapture {
            get {
                return ResourceManager.GetString("MinCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to System Tray.
        /// </summary>
        public static string MinTray {
            get {
                return ResourceManager.GetString("MinTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Clicks.
        /// </summary>
        public static string MouseClicks {
            get {
                return ResourceManager.GetString("MouseClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Audio.
        /// </summary>
        public static string NoAudio {
            get {
                return ResourceManager.GetString("NoAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Saved.
        /// </summary>
        public static string NotSaved {
            get {
                return ResourceManager.GetString("NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Webcam.
        /// </summary>
        public static string NoWebcam {
            get {
                return ResourceManager.GetString("NoWebcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Audio.
        /// </summary>
        public static string OnlyAudio {
            get {
                return ResourceManager.GetString("OnlyAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Output Folder.
        /// </summary>
        public static string OpenOutFolder {
            get {
                return ResourceManager.GetString("OpenOutFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutFolder {
            get {
                return ResourceManager.GetString("OutFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Padding.
        /// </summary>
        public static string PaddingX {
            get {
                return ResourceManager.GetString("PaddingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Padding.
        /// </summary>
        public static string PaddingY {
            get {
                return ResourceManager.GetString("PaddingY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Paused.
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause | Resume.
        /// </summary>
        public static string PauseResume {
            get {
                return ResourceManager.GetString("PauseResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause/Resume Recording.
        /// </summary>
        public static string PauseResumeRecording {
            get {
                return ResourceManager.GetString("PauseResumeRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording....
        /// </summary>
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record | Stop.
        /// </summary>
        public static string RecordStop {
            get {
                return ResourceManager.GetString("RecordStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshed.
        /// </summary>
        public static string Refreshed {
            get {
                return ResourceManager.GetString("Refreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Selector.
        /// </summary>
        public static string RegionSelector {
            get {
                return ResourceManager.GetString("RegionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from List.
        /// </summary>
        public static string RemoveFromList {
            get {
                return ResourceManager.GetString("RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Location.
        /// </summary>
        public static string SaveLocation {
            get {
                return ResourceManager.GetString("SaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        public static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenShot.
        /// </summary>
        public static string ScreenShot {
            get {
                return ResourceManager.GetString("ScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenShot Active Window.
        /// </summary>
        public static string ScreenShotActiveWindow {
            get {
                return ResourceManager.GetString("ScreenShotActiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenShot Desktop.
        /// </summary>
        public static string ScreenShotDesktop {
            get {
                return ResourceManager.GetString("ScreenShotDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenShot Saved.
        /// </summary>
        public static string ScreenShotSaved {
            get {
                return ResourceManager.GetString("ScreenShotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenShot Transforms.
        /// </summary>
        public static string ScreenShotTransforms {
            get {
                return ResourceManager.GetString("ScreenShotTransforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select FFMpeg Folder.
        /// </summary>
        public static string SelectFFMpegFolder {
            get {
                return ResourceManager.GetString("SelectFFMpegFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Folder.
        /// </summary>
        public static string SelectOutFolder {
            get {
                return ResourceManager.GetString("SelectOutFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show System Tray Notifications.
        /// </summary>
        public static string ShowSysNotify {
            get {
                return ResourceManager.GetString("ShowSysNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Delay (in ms).
        /// </summary>
        public static string StartDelay {
            get {
                return ResourceManager.GetString("StartDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Stop Recording.
        /// </summary>
        public static string StartStopRecording {
            get {
                return ResourceManager.GetString("StartStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Stopped.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforms.
        /// </summary>
        public static string Transforms {
            get {
                return ResourceManager.GetString("Transforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Proxy.
        /// </summary>
        public static string UseProxy {
            get {
                return ResourceManager.GetString("UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Proxy Authentication.
        /// </summary>
        public static string UseProxyAuth {
            get {
                return ResourceManager.GetString("UseProxyAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Frame Rate.
        /// </summary>
        public static string VarFrameRate {
            get {
                return ResourceManager.GetString("VarFrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Encoder.
        /// </summary>
        public static string VideoEncoder {
            get {
                return ResourceManager.GetString("VideoEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Saved.
        /// </summary>
        public static string VideoSaved {
            get {
                return ResourceManager.GetString("VideoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Source.
        /// </summary>
        public static string VideoSource {
            get {
                return ResourceManager.GetString("VideoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to Translate?.
        /// </summary>
        public static string WantToTranslate {
            get {
                return ResourceManager.GetString("WantToTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebCam.
        /// </summary>
        public static string WebCam {
            get {
                return ResourceManager.GetString("WebCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebCam View.
        /// </summary>
        public static string WebCamView {
            get {
                return ResourceManager.GetString("WebCamView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 560.
        /// </summary>
        public static string WindowHeight {
            get {
                return ResourceManager.GetString("WindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 420.
        /// </summary>
        public static string WindowWidth {
            get {
                return ResourceManager.GetString("WindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
